# Generated by Django 4.1 on 2022-08-21 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('courses', models.ManyToManyField(to='firstapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='firstapp.person')),
                ('position', models.CharField(max_length=50)),
                ('academic_title', models.CharField(default='', max_length=50)),
                ('academic_state', models.CharField(max_length=50)),
                ('courses', models.ManyToManyField(to='firstapp.course')),
            ],
            bases=('firstapp.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='firstapp.person')),
                ('group_id', models.IntegerField()),
                ('Group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.group')),
            ],
            bases=('firstapp.person',),
        ),
    ]
